# Memory Hog Application
# Intentionally OVER-provisioned - wastes cluster resources
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
  namespace: performance-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
      - name: memory-hog
        image: polinux/stress
        command: ["stress"]
        # Only uses ~150Mi of memory
        args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
        resources:
          requests:
            # Developer requested way too much "just to be safe"
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
