# VPA Operator Installation
# Installs the Vertical Pod Autoscaler Operator from OperatorHub
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-vertical-pod-autoscaler
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vertical-pod-autoscaler
  namespace: openshift-vertical-pod-autoscaler
spec:
  targetNamespaces:
  - openshift-vertical-pod-autoscaler
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vertical-pod-autoscaler
  namespace: openshift-vertical-pod-autoscaler
spec:
  channel: stable
  name: vertical-pod-autoscaler
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
