---
site:
  title: OpenShift Days - Ops Track
  url: https://github.com/jnewsome97/openshift-days-ops-track-showroom-v2
  start_page: openshift-days-ops-track::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/jnewsome97/rhdp_showroom_theme_execute/releases/download/rh-one-2025-execute/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

runtime:
  cache_dir: ./.cache/antora

antora:
  extensions:
    - require: ./content/lib/dev-mode.js
      enabled: false

output:
  dir: ./www

# Module attributes for ifdef conditionals in nav.adoc
# In production, these are injected by the showroom workload
# For local preview, enable all modules
asciidoc:
  attributes:
    toclevels: 2
    # Module flags - set to '' to enable, comment out to disable
    module_virt: ''
    module_acm: ''
    module_oadp: ''
    module_devhub: ''
    module_ols: ''
    module_security: ''
    module_waf: ''
    module_oidc: ''
    module_ldap: ''
    module_observability: ''
    module_performance: ''
    module_cloud_infra: ''
