---
site:
  title: OpenShift Days - Ops Track
  url: https://github.com/jnewsome97/openshift-days-ops-track-showroom-v2
  start_page: openshift-days-ops-track::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/jnewsome97/rhdp_showroom_theme/releases/download/v1.0.0-execute/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

runtime:
  cache_dir: ./.cache/antora

antora:
  extensions:
    - require: ./content/lib/dev-mode.js
      enabled: false

output:
  dir: ./www
