---
type: showroom

default_width: 30
persist_url_state: true

antora:
  name: openshift-days-ops-track
  version: main

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'

  - name: Terminal
    path: /wetty
    port: 443

  - name: OpenShift Docs
    url: 'https://docs.openshift.com/container-platform/latest/welcome/index.html'
